language: python

matrix:
  include:
    - python: 3.10
      env: TOXENV=py310

install:
  - pip install tox
  - pip install check-manifest
  - pip install flake8

script: tox

notifications:
  email: false